services:
    dev:
        container_name: phone_catalog
        build:
          context: .
          dockerfile: Dockerfile
        volumes:
          - ".:/app"
          - "/app/node_modules"
        ports:
          - 3001:3000
    prod:
        container_name: phone_catalog
        build:
          context: .
          dockerfile: Dockerfile
        volumes:
          - ".:/app"
          - "/app/node_modules"
        ports:
          - 3001:3000
